"""One-time setup for the Autolife knowledge base skill.

Run this after installing the skill. It asks for the API key, checks it
against the live gateway, and stores it in the skill's .env so every later
call works without any further configuration.

    python scripts/setup.py
    python scripts/setup.py --token kb_xxx        # non-interactive
    python scripts/setup.py --check               # just verify what is stored
"""

from __future__ import annotations

import argparse
import getpass
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kb_client import (  # noqa: E402
    DEFAULT_PUBLIC_URL,
    SKILL_ROOT,
    Config,
    KbError,
    PublicKbClient,
    load_dotenv,
)

ENV_PATH = os.path.join(SKILL_ROOT, ".env")
PLACEHOLDER_VALUES = {"", "your_token_here", "kb_xxx", "changeme"}


def read_env() -> dict[str, str]:
    """Parse the existing .env into a dict, preserving unrelated keys."""
    data: dict[str, str] = {}
    if not os.path.exists(ENV_PATH):
        return data
    with open(ENV_PATH, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            data[key.strip()] = value.strip()
    return data


def write_env(data: dict[str, str]) -> None:
    lines = [
        "# Autolife knowledge base skill - local configuration.",
        "# Generated by scripts/setup.py. Do not commit this file.",
        "",
    ]
    for key, value in data.items():
        lines.append(f"{key}={value}")
    with open(ENV_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


def verify(token: str, public_url: str) -> str | None:
    """Return None when the token works, else a human-readable reason."""
    os.environ["KB_API_TOKEN"] = token
    os.environ["KB_PUBLIC_URL"] = public_url
    try:
        client = PublicKbClient(Config())
        results = client.search("ping", top_k=1)
    except KbError as exc:
        return str(exc)
    except Exception as exc:  # pragma: no cover - network layer surprises
        return f"{type(exc).__name__}: {exc}"
    if not results:
        return "密钥有效，但检索没有返回任何内容（知识库可能是空的）"
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="配置 Autolife 知识库 skill")
    parser.add_argument("--token", help="直接提供 API 密钥（非交互）")
    parser.add_argument("--public-url", default=None, help=f"覆盖网关地址（默认 {DEFAULT_PUBLIC_URL}）")
    parser.add_argument("--check", action="store_true", help="只校验已保存的密钥")
    parser.add_argument("--force", action="store_true", help="即使已配置也重新设置")
    args = parser.parse_args(argv)

    load_dotenv()
    env = read_env()
    public_url = args.public_url or env.get("KB_PUBLIC_URL") or DEFAULT_PUBLIC_URL

    stored = env.get("KB_API_TOKEN", "")
    already_ok = stored.strip() not in PLACEHOLDER_VALUES

    if args.check:
        if not already_ok:
            print("尚未配置 KB_API_TOKEN。请先运行：python scripts/setup.py")
            return 1
        problem = verify(stored, public_url)
        if problem:
            print(f"密钥校验失败：{problem}")
            return 1
        print(f"配置正常（{public_url}）")
        return 0

    if already_ok and not args.force and not args.token:
        problem = verify(stored, public_url)
        if problem is None:
            print("已经配置好了，无需重复设置。")
            print(f"  网关：{public_url}")
            print(f"  密钥：{stored[:10]}…{stored[-4:]}")
            print("如需更换，请加 --force。")
            return 0
        print(f"已保存的密钥校验失败：{problem}")
        print("请重新输入。\n")

    token = args.token
    if not token:
        print("=" * 62)
        print(" Autolife 知识库 - 配置 API 密钥")
        print("=" * 62)
        print(f" 网关地址：{public_url}")
        print()
        print(" 请粘贴管理员分发给你的 API 密钥（通常以 kb_ 开头）。")
        print(" 输入时不会回显，粘贴后直接回车即可。")
        print()
        try:
            token = getpass.getpass(" API 密钥: ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\n已取消。")
            return 1

    if not token:
        print("没有输入密钥，已取消。")
        return 1

    print("\n正在校验…")
    problem = verify(token, public_url)
    if problem:
        print(f"校验失败：{problem}")
        print("请确认密钥是否正确、是否已被吊销，以及网关地址是否可达。")
        return 1
    print("校验通过。")

    env["KB_PUBLIC_URL"] = public_url
    env["KB_API_TOKEN"] = token
    env.setdefault("KB_TOP_K", "5")
    env.setdefault("KB_MAX_CHARS", "12000")
    write_env(env)

    print(f"\n已写入 {ENV_PATH}")
    print("\n下一步：")
    print('  python scripts/retrieve_kb.py "机器人视觉无法启动"')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
